import './globals.css'
import { Inter } from 'next/font/google'
import { foundry } from 'viem/chains'
import { WagmiConfig, configureChains, createConfig } from 'wagmi'
import { publicProvider } from 'wagmi/providers/public'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  


  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
